### ISSUE TITLE
remove redundant from_iter and vec! allocations

### ISSUE THREAD

**Issue by washbin** [CaffeineDuck/jBREAD#1]
We could remove the `from_iter` and `into_iter` part since using `HashMap::from` automatically does the conversion with a array of tuples. possibly removing a vector allocation as well.

https://github.com/CaffeineDuck/jBREAD/blob/3d4c7bcebe06f4c343abe443a0e791e42e3734ac/src/scanner.rs#LL39C5-L39C5

```rs
HashMap::from([
  ("en", "tea"),
  ("np", "chiya")
])
```

**Comment by washbin** [comment]
run clippy pliz

**Comment by CaffeineDuck** [comment]
Thanks for informing, will fix.
